import pandas as pd
from adapters.analytics_service import AnalyticsService


class RevenueAnalytics:
    """Revenue analytics including monthly trends and revenue per customer segment."""

    def __init__(self, service: AnalyticsService) -> None:
        self.service = service

    def get_monthly_revenue(self) -> pd.DataFrame:
        """Monthly gross revenue (items + freight) for delivered orders."""
        query = """
        SELECT
            strftime('%Y-%m', o.order_purchase_timestamp) AS month,
            COUNT(DISTINCT o.order_id)                     AS orders,
            ROUND(SUM(oi.price + oi.freight_value), 2)    AS total_revenue,
            ROUND(AVG(oi.price + oi.freight_value), 2)    AS avg_order_value
        FROM orders o
        JOIN order_items oi ON o.order_id = oi.order_id
        WHERE o.order_status = 'delivered'
        GROUP BY 1
        ORDER BY 1;
        """
        return self.service.execute_query(query)

    def get_revenue_by_customer_type(self) -> pd.DataFrame:
        """Compare total revenue generated by one-time vs repeat customers."""
        query = """
        WITH customer_orders AS (
            SELECT
                c.customer_unique_id,
                COUNT(DISTINCT o.order_id) AS total_orders
            FROM customers c
            JOIN orders o ON c.customer_id = o.customer_id
            WHERE o.order_status = 'delivered'
            GROUP BY c.customer_unique_id
        ),
        customer_revenue AS (
            SELECT
                c.customer_unique_id,
                SUM(oi.price + oi.freight_value) AS lifetime_value
            FROM customers c
            JOIN orders o ON c.customer_id = o.customer_id
            JOIN order_items oi ON o.order_id = oi.order_id
            WHERE o.order_status = 'delivered'
            GROUP BY c.customer_unique_id
        )
        SELECT
            CASE WHEN co.total_orders = 1 THEN 'One-Time' ELSE 'Repeat' END AS customer_type,
            COUNT(co.customer_unique_id)               AS customers,
            ROUND(SUM(cr.lifetime_value), 2)           AS total_revenue,
            ROUND(AVG(cr.lifetime_value), 2)           AS avg_lifetime_value
        FROM customer_orders co
        JOIN customer_revenue cr ON co.customer_unique_id = cr.customer_unique_id
        GROUP BY 1;
        """
        return self.service.execute_query(query)
